environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  # - TARGET: i686-pc-windows-msvc
  # - TARGET: i686-pc-windows-gnu
  GH_TOKEN:
    secure: nHB4fVo+y/Aak+L0nYfrT8Rcs8OfUNm0F2xcIVFVYJ9ehf0CzvCmSMUvWguM0kKp

install:
  - SET PATH=C:\Python27;C:\Python27\Scripts;%PATH%;%APPDATA%\Python\Scripts
  - pip install travis-cargo --user

  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\MinGW\bin

  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --target %TARGET%
  - cargo doc --no-deps

after_test:
  - travis-cargo doc-upload
